name: webview_base
description: A new Flutter project.
version: 1.0.0+1

# # iOS
# version: 1.0.2+5
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  #for push notification of firebase
  flutter_local_notifications: ^19.5.0

  #to create webview
  flutter_inappwebview: ^6.1.5

  #to get theme modes set by user
  shared_preferences: ^2.3.2

  # lottie icons
  lottie: ^3.1.3

  #draw svg icons
  flutter_svg: #^1.1.0

  # state management
  provider: ^6.0.5

  # launch web URLs
  url_launcher: ^6.3.1

  # for handling permissions for downloading tasks
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.4

  # to download files
  dio: ^5.2.1+1

  device_info_plus: ^12.3.0

  #firebase
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4

  # update badge for a lot of android devices
  fluttertoast: ^9.0.0
  package_info_plus: ^9.0.0
  flutter_app_badge_control: ^0.0.2
  share_plus: ^12.0.1
  open_file: ^3.5.10
  version: ^3.0.2
  app_tracking_transparency: ^2.0.6+1
  flutter_contacts: ^1.1.7+1
  app_links: ^6.4.0
  flutter_dotenv: ^6.0.0

dependency_overrides:
  permission_handler_apple: 9.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

  rename_app: ^1.6.5

  # run: dart run change_app_package_name:main com.new.package.name
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.4.6

  # run: dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#2E2C2C"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  background_color_ios: "#2E2C2C"
  remove_alpha_ios: true
  image_path_ios: "assets/images/app_icon_ios.png"

  # run: flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#2E2C2C"
  image: assets/images/splash_content.png
  branding: assets/images/splash_brand.png # This should be an image containing your text
  branding_bottom_padding: 50

  android_12:
    image: assets/images/splash_content_android_12.png
    color: "#2E2C2C"
    branding: assets/images/splash_brand_android_12.png

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - lib/config/.env.dev
    - lib/config/.env.staging
    - lib/config/.env.prod
  fonts:
    - family: SegUI
      fonts:
        - asset: assets/fonts/segoeui.ttf
        - asset: assets/fonts/seguisb.ttf
          weight: 900
